### ISSUE TITLE
logstash forwarder giving big exception and failing

### ISSUE THREAD

**Issue by teu** [elasticsearch/logstash-forwarder#187]
Hi 

having a problem with the forwarder, the version is about 1,5 months old (kind of difficult to check, as there is no version output of the program itself)

```
2014/04/02 12:38:59.101616 Registrar received 6 events
2014/04/02 12:39:03.359290 Registrar received 2 events
2014/04/02 12:39:09.427078 Registrar received 4 events
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7fc301ac2425


goroutine 1 [runnable]:
syscall.Syscall()
	/usr/local/go/src/pkg/syscall/asm_linux_amd64.s:36 +0x64
syscall.open(0x6334b0, 0x17, 0x80242, 0x1b6, 0x0, ...)
	/usr/local/go/src/pkg/syscall/zerrors_linux_amd64.go:1536 +0x9a
syscall.Open(0x6334b0, 0x17, 0x80242, 0x1b6, 0x8, ...)
	/usr/local/go/src/pkg/syscall/syscall_linux.go:23 +0x5c
os.OpenFile(0x6334b0, 0x17, 0x242, 0x1b6, 0x0, ...)
	/usr/local/go/src/pkg/os/file_unix.go:77 +0x71
os.Create(0x6334b0, 0x17, 0xb58b0b725b415d3c, 0x0, 0x0, ...)
	/usr/local/go/src/pkg/os/file.go:239 +0x52
main.WriteRegistry(0xc200138300, 0x633470, 0x13)
	/var/www/logstash-forwarder/registrar_other.go:12 +0x32
main.Registrar(0xc2000b0700)
	/var/www/logstash-forwarder/registrar.go:33 +0x1f8
main.main()
	/var/www/logstash-forwarder/logstash-forwarder.go:72 +0x3d4

goroutine 2 [syscall]:

goroutine 4 [sleep]:
time.Sleep(0x2540be400)
	/usr/local/go/src/pkg/runtime/ztime_linux_amd64.c:19 +0x2f
main.Prospect(0xc200091b40, 0x1, 0x4, 0xc200091b80, 0xc2000a6620, ...)
	/var/www/logstash-forwarder/prospector.go:34 +0x335
created by main.main
	/var/www/logstash-forwarder/logstash-forwarder.go:63 +0x322

goroutine 5 [select]:
main.Spool(0xc2000a6620, 0xc2000b0690, 0x400, 0x12a05f200)
	/var/www/logstash-forwarder/spooler.go:26 +0x3fa
created by main.main
	/var/www/logstash-forwarder/logstash-forwarder.go:67 +0x38d

goroutine 6 [chan receive]:
main.Publishv1(0xc2000b0690, 0xc2000b0700, 0xc2000b05b0)
	/var/www/logstash-forwarder/publisher1.go:42 +0xbb
created by main.main
	/var/www/logstash-forwarder/logstash-forwarder.go:69 +0x3c1

goroutine 8 [runnable]:
syscall.Syscall()
	/usr/local/go/src/pkg/syscall/asm_linux_amd64.s:36 +0x64
syscall.read(0x4, 0xc2000ed000, 0x4000, 0x4000, 0x0, ...)
	/usr/local/go/src/pkg/syscall/zerrors_linux_amd64.go:2337 +0x70
syscall.Read(0x4, 0xc2000ed000, 0x4000, 0x4000, 0x0, ...)
	/usr/local/go/src/pkg/syscall/syscall_unix.go:132 +0x5a
os.(*File).read(0xc2000002a8, 0xc2000ed000, 0x4000, 0x4000, 0x0, ...)
	/usr/local/go/src/pkg/os/file_unix.go:174 +0x60
os.(*File).Read(0xc2000002a8, 0xc2000ed000, 0x4000, 0x4000, 0x0, ...)
	/usr/local/go/src/pkg/os/file.go:95 +0x96
bufio.(*Reader).fill(0xc2000b30c0)
	/usr/local/go/src/pkg/bufio/bufio.go:79 +0x10c
bufio.(*Reader).ReadSlice(0xc2000b30c0, 0x533bf60a, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/pkg/bufio/bufio.go:262 +0x202
bufio.(*Reader).ReadLine(0xc2000b30c0, 0x0, 0x0, 0x0, 0x43c800, ...)
	/usr/local/go/src/pkg/bufio/bufio.go:293 +0x61
main.(*Harvester).readline(0xc200076960, 0xc2000b30c0, 0x2540be400, 0x3a07565f55e8, 0x0, ...)
	/var/www/logstash-forwarder/harvester.go:123 +0x70
main.(*Harvester).Harvest(0xc200076960, 0xc2000a6620)
	/var/www/logstash-forwarder/harvester.go:45 +0x2d7
created by main.resume_tracking
	/var/www/logstash-forwarder/prospector.go:62 +0x3de

goroutine 9 [finalizer wait]:

goroutine 10 [runnable]:
syscall.Syscall()
	/usr/local/go/src/pkg/syscall/asm_linux_amd64.s:36 +0x64
syscall.read(0x7, 0xc2001e4000, 0x4000, 0x4000, 0x0, ...)
	/usr/local/go/src/pkg/syscall/zerrors_linux_amd64.go:2337 +0x70
syscall.Read(0x7, 0xc2001e4000, 0x4000, 0x4000, 0x0, ...)
	/usr/local/go/src/pkg/syscall/syscall_unix.go:132 +0x5a
os.(*File).read(0xc200000300, 0xc2001e4000, 0x4000, 0x4000, 0x0, ...)
	/usr/local/go/src/pkg/os/file_unix.go:174 +0x60
os.(*File).Read(0xc200000300, 0xc2001e4000, 0x4000, 0x4000, 0x0, ...)
	/usr/local/go/src/pkg/os/file.go:95 +0x96
bufio.(*Reader).fill(0xc20014e660)
	/usr/local/go/src/pkg/bufio/bufio.go:79 +0x10c
bufio.(*Reader).ReadSlice(0xc20014e660, 0x533bf60a, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/pkg/bufio/bufio.go:262 +0x202
bufio.(*Reader).ReadLine(0xc20014e660, 0x0, 0x0, 0x0, 0x100076b00, ...)
	/usr/local/go/src/pkg/bufio/bufio.go:293 +0x61
main.(*Harvester).readline(0xc200135810, 0xc20014e660, 0x2540be400, 0xc200136070, 0x0, ...)
	/var/www/logstash-forwarder/harvester.go:123 +0x70
main.(*Harvester).Harvest(0xc200135810, 0xc2000a6620)
	/var/www/logstash-forwarder/harvester.go:45 +0x2d7
created by main.prospector_scan
	/var/www/logstash-forwarder/prospector.go:130 +0xa2e
rax     0x0
rbx     0xb
rcx     0xffffffffffffffff
rdx     0x6
rdi     0x18d
rsi     0x1ac
rbp     0xc20007e800
rsp     0x7fc2f1a7f688
r8      0x7fc2f1a80700
r9      0x616e7520796c6972
r10     0x8
r11     0x206
r12     0x7fc2ec0008c0
r13     0x7fc2f1a809c0
r14     0x0
r15     0x3
rip     0x7fc301ac2425
rflags  0x206
cs      0x33
fs      0x0
gs      0x0
runtime: panic before malloc heap initialized
fatal error: runtime: cannot allocate heap metadata
runtime: panic before malloc heap initialized
fatal error: runtime: cannot allocate heap metadata
runtime: panic before malloc heap initialized
fatal error: runtime: cannot allocate heap metadata
runtime: panic before malloc heap initialized
fatal error: runtime: cannot allocate heap metadata
runtime: panic before malloc heap initialized
fatal error: runtime: cannot allocate heap metadata

```

**Comment by jordansissel** [comment]
> runtime/cgo: pthread_create failed: Resource temporarily unavailable

Sounds like your system is out of memory, or something?

If there's a bug we can fix, I'll try to fix it, but this sounds like a server resource problem.
